### ISSUE TITLE
Blogging on python.ie

### ISSUE THREAD

**Issue by whykay** [PythonIreland/website#31]
Currently it's just a page when in admin panel.

Can this be switched to a blog so we can add posts? The /blog/ is currently empty.

Explorer > Blog

**Comment by nlaurance** [comment]
just add a blog post as a sub page of the blog. display should be ok

**Comment by whykay** [comment]
@nlaurance: Is it "Explorer" > "Python Ireland" > "Blog"?
And then click on "+" to add a blog post?

And is this the blog link? http://python.ie/blog/

**Comment by diarmuidbourke** [comment]
Please hold off on this as it won't work. I have a pending patch which
enables the blog. I'll post it up later today. For now feel free to add it
to the end of the homepage.

**Comment by whykay** [comment]
Thanks. I'm curious that is all, I wasn't going to post a blog until it gets thumbs up from you and Diarmuid. :-)
