### ISSUE TITLE
Polling meetup.com should be a background job

### ISSUE THREAD

**Issue by diarmuidbourke** [PythonIreland/website#37]
Utilise heroku worker processes to poll meetup.com for new meetup changes.

Heroku worker documentation: https://devcenter.heroku.com/articles/background-jobs-queueing

**Comment by saoili** [comment]
I'm going to try taking a look at this

**Comment by saoili** [comment]
Okay, think I'm going to have to bail on this ticket. Fun as this is, I need to go to bed now and back to real life tomorrow. A few pointers for whoever picks it up

- looks like you might need a verified heroku account to run the python-rq worker (https://devcenter.heroku.com/articles/python-rq -> https://devcenter.heroku.com/articles/python-rq gives verification required error)
- update in pthonie/meetups/utils is called from pythonie/core/templates/core_tags.py, each time the meetups section of the site is loaded. It checks (in redis) if we've updated from meetups.com in the past hour and updates if we haven't.
- The aim here is to use a cron job (http://www.thesitewizard.com/general/set-cron-job.shtml) running on the heroku instance to call this update every hour. Probably getting a worker to run it as per stuff Diarmuid links to above.

**Comment by andrewmccarthy** [comment]
Fixed in #74 and #76.
