### ISSUE TITLE
Speaker page should cater for ordering of speakers

### ISSUE THREAD

**Issue by diarmuidbourke** [PythonIreland/website#40]
Currently they are listed in the reverse chronological order they were inserted into Lanyrd. This isn't great when we want to highlight keynotes and opening speakers.

The current solution is a hack in the speakers template page (search for 'dragons' for an explanation).

One possible solution is to allow for an ordered list of promoted speakers to be set on the speaker page via the admin interface. Then use this list when rendering the page to pop speakers to the front of the list.

**Comment by patclaffey** [comment]
Here is lanyrd speaker url:
http://lanyrd.com/2015/pyconie/speakers/212e6614efbc8620.v1.json

**Comment by diarmuidbourke** [comment]
wont fix, we use attendify now
