### ISSUE TITLE
Create sample DB for dev version of site

### ISSUE THREAD

**Issue by saoili** [PythonIreland/website#41]
Contributing would be much easier if we had a sample DB. Would it be possible to take a copy of the production one and change any passwords etc?

**Comment by madkite** [comment]
Or at least provide some instruction how to get something differ from "Welcome to your new Wagtail site!".

**Comment by saoili** [comment]
Pull request https://github.com/PythonIreland/website/pull/43 created

**Comment by diarmuidbourke** [comment]
@saoili 's change makes more sense than to provide a sample database which would need to be maintained and migrated along with the production database. 

I do agree that there are certain instances where sample data is very useful during development for highlighting potential content issues. I just don't think the extra maintenance is worth the gain right now.
