### ISSUE TITLE
Allow different heading sizes

### ISSUE THREAD

**Issue by diarmuidbourke** [PythonIreland/website#57]
Currenly all 'simple page' headings show up as h3's

**Comment by davgibbs** [comment]
Hi @diarmuidbourke , I started looking into this, just have a couple of questions:
1) Is the "simple page" in use anywhere on the live site as I think changing it would involve a data migration
2) Is what is needed the ability to do something like the below in the simple_page.html:
```
                        {% for block in self.body %}
                            {% if block.block_type == 'h2' %}
                                <h2>{{ block.value }}</h2>
                            {% elif block.block_type == 'h3' %}
                                <h3>{{ block.value }}</h3>
                            {% elif block.block_type == 'h4' %}
                                <h4>{{ block.value }}</h4>
                            {% else %}
                                <section class="block-{{ block.block_type }}">
                                    {{ block }}
                                </section>
                            {% endif %}
                        {% endfor %}
```

**Comment by diarmuidbourke** [comment]
It is in use on the site, but I don't think a migration is required. It's just a template change.

I guess the template should just be 
`{% if block.block_type in ['h1', ... 'h6'] %}
     <{{ block.block_type }}>{{ block.value }}</{{ block.block_type }}>
  {% else %}
      <section class="block-{{ block.block_type }}">
          {{ block }}
      </section>
  {% endif %}`

??

**Comment by davgibbs** [comment]
Hi @diarmuidbourke , but I think just changing the template won't add the h2, h3, h4 options to the wagtail admin (as replacement of "Heading")?

![wagtail_simplepage](https://cloud.githubusercontent.com/assets/13841059/15426354/f281dc32-1e85-11e6-89ab-996ffc804180.png)

**Comment by diarmuidbourke** [comment]
Oh, that heading can remain as h1 or whatever it's existing size is. I meant to specify that this is for the content of the 'paragraph'.

**Comment by davgibbs** [comment]
Ah ok. The paragraph headings seem to be working for me without any code changes. It puts it all inside a div with class 'rich-text'
```
<article>
    <h3>Default Heading</h3>
        <section class="block-paragraph">
            <div class="rich-text"><h2>Heading 2</h2><p>text h2</p><h5>H5</h5><p>text h5</p></div>
        </section>
</article>
```

**Comment by diarmuidbourke** [comment]
seems to work...
