### ISSUE TITLE
404 Page Content is outside container

### ISSUE THREAD

**Issue by davgibbs** [PythonIreland/website#58]
When I try to access a page that is not found on the website, I get a 404 error. For example at URL:
http://python.ie/a/

This is good, but the page content is outside the container and looks funny:
![pyie_404page](https://cloud.githubusercontent.com/assets/13841059/15968691/bd05f610-2f24-11e6-9e92-6f73ebc27374.png)

So I think a small fix to add a container div within the content template tag on 404.html would be good:
```
{% block content %}
    <div class="container">
        <h1>Page not found</h1>

        <h2>Sorry, this page could not be found.</h2>
    </div>
{% endblock %}
```
Should I add a Pull Request for this?

**Comment by diarmuidbourke** [comment]
Cheers for that! I merged and deployed it there.

**Comment by davgibbs** [comment]
Great, looks like the change is on the live site now. Thanks for merging @diarmuidbourke !
